### PR TITLE
Update egg-pterodactyl-purpur--geyser--floodgate.json

### PR DESCRIPTION
**Pull request by Dobbelklick**
# Description

Missing -o parameter in curl lead to failed download of Geyser plugin.

## Checklist for all submissions

* [ x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [ x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [ x] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [ ] The egg was exported from the panel

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
Please at least export from a panel. And then replace hhe full file. I will then take care of the pelican one.

**Comment by Dobbelklick** [comment]
I'm sorry this is my first pull request. I don't understand the difference "exporting from a panel" makes. It would be the same diff as far as I can tell. I just fixed a small syntax error.

Or is there some kind of background testing happening during exporting? If so, I didn't get any errors. :)

**Comment by QuintenQVD0** [comment]
> I'm sorry this is my first pull request. I don't understand the difference "exporting from a panel" makes. It would be the same diff as far as I can tell. I just fixed a small syntax error.
> 
> Or is there some kind of background testing happening during exporting? If so, I didn't get any errors. :)

It formats the egg and changes some timestamp fields.

**Comment by Dobbelklick** [comment]
done :)

**Pull request merged**
