### PR TITLE
Create egg-bungeecord.json

### PR DESCRIPTION
**Pull request by Link0Darck**
Change in code:
- Added Bungeecord
- Added Java 21
- all `ghcr.io\/pterodactyl\/yolks:` are replaced by: `ghcr.io\/parkervcp\/yolks:`
- modify code respecting the code of `parkervcp`

# Description

## Checklist for all submissions

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [ ] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [ ] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [ ] The egg was exported from the panel

## New egg Submissions

1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [ ] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [ ] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [ ] You verify that the start command applied does not use a shell script
    * [ ] If some script is needed then it is part of a current yolk or a PR to add one
6. [x] The egg was exported from the panel

### CODE REVIEW

**Comment by Link0Darck** [comment]
Gifts and functional 😊

**Comment by QuintenQVD0** [comment]
This still is a stock egg so no real need for it here?

**Comment by Link0Darck** [comment]
> This still is a stock egg so no real need for it here?

it's for those who want it can always be useful

**Comment by QuintenQVD0** [comment]
sorry but no, we do not want to add stock eggs here as they quickly become outdated or out of sync with the panel ones.

**Pull request closed without merging**
