### PR TITLE
Update egg-spigot.json

### PR DESCRIPTION
**Pull request by Link0Darck**
add java version 21 and works

# Description

## Checklist for all submissions

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [ ] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [ ] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [x] The egg was exported from the panel

## New egg Submissions

1. [x] Does your submission pass tests (server is connectable)?
2. [ ] Does your egg use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [ ] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [ ] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [ ] You verify that the start command applied does not use a shell script
    * [ ] If some script is needed then it is part of a current yolk or a PR to add one
6. [x] The egg was exported from the panel

### CODE REVIEW

**Comment by Link0Darck** [comment]
Capture d'écran 2024-05-05 193100

**Comment by Link0Darck** [comment]
I just saw how the egg is made then I add Java 21 from yolk then modify the script and test on my panel and export the json

**Comment by QuintenQVD0** [comment]
Please adapt your changes to this PR: https://github.com/pelican-eggs/minecraft/pull/4

(The images all changed as we will not be using the pterodactyl ones anymore)

**Comment by Link0Darck** [comment]
> Please adapt your changes to this PR: #4
> 
> (The images all changed as we will not be using the pterodactyl ones anymore)

It's good I did it then I tested it on my machine and it works

**Review by QuintenQVD0 — APPROVED** [review]
LGTM! thanks

**Pull request merged**
